// components/dashboard/QuizGenerator.js
// AI-Powered Quiz Generation Component

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { notify } from "../../components/Notifications";

export default function QuizGenerator({ isOpen, onClose, onSave, selectedClass }) {
    const [topic, setTopic] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedQuiz, setGeneratedQuiz] = useState(null);

    if (!isOpen) return null;

    const handleGenerate = async () => {
        if (!topic) return;
        setIsGenerating(true);
        // Simulate AI logic
        setTimeout(() => {
            const quiz = {
                id: `quiz_${Date.now()}`,
                title: `${topic} Mastery Quiz`,
                subject: selectedClass?.subject || "General",
                questions: [
                    { id: 1, text: `What is the primary law governing ${topic}?`, options: ["Option A", "Option B", "Option C", "Option D"], correct: 0 },
                    { id: 2, text: `In the context of ${topic}, how does X affect Y?`, options: ["Option A", "Option B", "Option C", "Option D"], correct: 2 }
                ]
            };
            setGeneratedQuiz(quiz);
            setIsGenerating(false);
            notify("Quiz generated by Elora ✨", "success");
        }, 1500);
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 sm:p-12">
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={onClose}
                className="absolute inset-0 bg-neutral-900/40 backdrop-blur-md"
            />

            <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                className="relative w-full max-w-xl bg-white dark:bg-neutral-950 rounded-[2.5rem] shadow-premium-xl border-premium overflow-hidden"
            >
                <div className="p-10">
                    <div className="flex items-center gap-3 mb-6">
                        <div className="w-10 h-10 rounded-2xl bg-indigo-600 flex items-center justify-center text-white text-xl shadow-premium-md">✨</div>
                        <h3 className="text-2xl font-extrabold text-neutral-900 dark:text-neutral-50 tracking-tight font-[var(--font-outfit)]">Quiz Genius</h3>
                    </div>

                    {!generatedQuiz ? (
                        <div className="space-y-6">
                            <p className="text-neutral-500 text-sm leading-relaxed">
                                Tell Elora what topic you're teaching, and she'll generate a multi-tiered quiz optimized for {selectedClass?.level || 'your students'}.
                            </p>
                            <div className="space-y-2">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-neutral-400 ml-4">Quiz Topic</label>
                                <input
                                    value={topic}
                                    onChange={e => setTopic(e.target.value)}
                                    placeholder="e.g. Newton's Third Law, Photosynthesis"
                                    className="w-full bg-neutral-50 dark:bg-neutral-900 border-premium rounded-2xl px-6 py-4 text-sm font-medium focus:ring-2 focus:ring-primary-500 outline-none transition-all"
                                />
                            </div>
                            <button
                                onClick={handleGenerate}
                                disabled={isGenerating || !topic}
                                className="w-full py-4 bg-neutral-900 dark:bg-neutral-50 text-white dark:text-neutral-900 rounded-2xl text-[10px] font-bold uppercase tracking-widest shadow-premium-md hover:opacity-90 transition-all disabled:opacity-30 flex items-center justify-center gap-2"
                            >
                                {isGenerating ? (
                                    <>
                                        <span className="animate-spin text-lg">◌</span> Generating Intelligence...
                                    </>
                                ) : (
                                    "Generate Quiz Now →"
                                )}
                            </button>
                        </div>
                    ) : (
                        <div className="space-y-6">
                            <div className="p-6 bg-emerald-50 dark:bg-emerald-500/10 border-premium border-emerald-200 dark:border-emerald-500/30 rounded-2xl">
                                <h4 className="font-bold text-emerald-800 dark:text-emerald-400 mb-1">{generatedQuiz.title}</h4>
                                <p className="text-xs text-emerald-600 dark:text-emerald-500">{generatedQuiz.questions.length} adaptive questions drafted.</p>
                            </div>

                            <div className="max-h-48 overflow-y-auto space-y-3 pr-2 scrollbar-hide">
                                {generatedQuiz.questions.map((q, i) => (
                                    <div key={i} className="p-4 bg-neutral-50 dark:bg-neutral-900 border-premium rounded-xl text-xs">
                                        <b>Q{i + 1}:</b> {q.text}
                                    </div>
                                ))}
                            </div>

                            <div className="flex gap-4 pt-4">
                                <button
                                    onClick={() => setGeneratedQuiz(null)}
                                    className="flex-1 py-3 bg-white dark:bg-neutral-900 border-premium text-neutral-500 rounded-xl text-[10px] font-bold uppercase tracking-widest hover:bg-neutral-50"
                                >
                                    Re-generate
                                </button>
                                <button
                                    onClick={() => { onSave(generatedQuiz); onClose(); }}
                                    className="flex-1 py-3 bg-neutral-900 dark:bg-neutral-50 text-white dark:text-neutral-900 rounded-xl text-[10px] font-bold uppercase tracking-widest shadow-premium-md"
                                >
                                    Save & Assign
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </motion.div>
        </div>
    );
}
