import PptxGenJS from "pptxgenjs";

function clampStr(v, max = 120000) {
  if (typeof v !== "string") return "";
  const s = v.trim();
  return s.length <= max ? s : s.slice(0, max);
}

function normalizeTheme(v) {
  const x = (v || "").toString().trim().toLowerCase();
  return x === "light" ? "light" : "dark";
}

function splitOutlineToSlides(text) {
  const lines = (text || "").split("\n").map((l) => l.replace(/\r/g, ""));
  const slides = [];
  let current = { title: "Slide", bullets: [], visuals: [] };

  const push = () => {
    if (current.title || current.bullets.length || current.visuals.length) slides.push(current);
    current = { title: "Slide", bullets: [], visuals: [] };
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    if (/^#{1,6}\s+/.test(line)) {
      push();
      current.title = line.replace(/^#{1,6}\s+/, "").trim() || "Slide";
      continue;
    }

    if (/^Slide\s*\d+[:\-]/i.test(line)) {
      push();
      current.title = line.replace(/^Slide\s*\d+[:\-]\s*/i, "").trim() || "Slide";
      continue;
    }

    if (/^\*\*Visual/i.test(line)) {
      // **Visual ideas:** or similar
      continue;
    }

    if (/^[-*]\s+/.test(line)) {
      const b = line.replace(/^[-*]\s+/, "").trim();
      if (b.toLowerCase().startsWith("visual")) current.visuals.push(b);
      else current.bullets.push(b);
      continue;
    }

    // Default -> bullet
    current.bullets.push(line);
  }

  push();
  return slides.filter((s) => s.title || s.bullets.length || s.visuals.length).slice(0, 14);
}

function toSlidesFromArtifact(artifact) {
  if (!artifact || artifact.type !== "slides") return null;
  const slides = Array.isArray(artifact.slides) ? artifact.slides : [];
  return {
    title: artifact.title || "Slides",
    slides: slides.map((s) => ({
      title: (s && s.title) || "Slide",
      bullets: Array.isArray(s?.bullets) ? s.bullets : [],
      visuals: Array.isArray(s?.visuals) ? s.visuals : [],
      layoutHint: s?.layoutHint ? String(s.layoutHint) : "",
      teacherNotes: s?.teacherNotes ? String(s.teacherNotes) : "",
    })),
  };
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const title = clampStr(req.body?.title || "Elora Slides", 120);
    const theme = normalizeTheme(req.body?.theme);

    const artifact = req.body?.artifact || null;
    const fromArtifact = toSlidesFromArtifact(artifact);

    const content = clampStr(req.body?.content || "", 120000);
    const outlineSlides = fromArtifact?.slides || splitOutlineToSlides(content);

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.author = "Elora";

    // Theme palette
    const bg = theme === "dark" ? "0B1020" : "FFFFFF";
    const card = theme === "dark" ? "111A33" : "F3F6FF";
    const text = theme === "dark" ? "F8FAFC" : "0F172A";
    const muted = theme === "dark" ? "CBD5E1" : "334155";
    const accent = "6366F1"; // indigo

    // Helper: slide base
    const applyBase = (slide) => {
      slide.background = { color: bg };
      // header bar
      slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.33, h: 0.65, fill: { color: accent } });
    };

    // Title slide
    {
      const s0 = pptx.addSlide();
      applyBase(s0);

      s0.addText("Elora", {
        x: 0.8, y: 0.15, w: 3.5, h: 0.35,
        fontSize: 16, bold: true, color: "FFFFFF"
      });

      s0.addShape(pptx.ShapeType.roundRect, {
        x: 0.8, y: 1.3, w: 11.8, h: 4.6,
        fill: { color: card }, line: { color: accent, transparency: 70 }, radius: 18
      });

      s0.addText(title, {
        x: 1.2, y: 2.1, w: 11, h: 0.9,
        fontSize: 40, bold: true, color: text
      });

      s0.addText("Generated by Elora • Classroom-ready", {
        x: 1.2, y: 3.1, w: 11, h: 0.4,
        fontSize: 16, color: muted
      });
    }

    // Content slides
    outlineSlides.slice(0, 12).forEach((s) => {
      const slide = pptx.addSlide();
      applyBase(slide);

      // Title
      slide.addText(s.title || "Slide", {
        x: 0.8, y: 0.9, w: 12, h: 0.6,
        fontSize: 30, bold: true, color: text
      });

      // Main content card
      slide.addShape(pptx.ShapeType.roundRect, {
        x: 0.8, y: 1.6, w: 8.2, h: 5.4,
        fill: { color: card }, line: { color: accent, transparency: 80 }, radius: 18
      });

      const bullets = (Array.isArray(s.bullets) ? s.bullets : []).slice(0, 7).map((b) => b.trim()).filter(Boolean);
      const bulletText = bullets.length ? bullets.map((b) => `• ${b}`).join("\n") : "• (Add content)";

      slide.addText(bulletText, {
        x: 1.15, y: 2.0, w: 7.5, h: 4.8,
        fontSize: 18, color: text, valign: "top"
      });

      // Visual/teacher notes card
      slide.addShape(pptx.ShapeType.roundRect, {
        x: 9.25, y: 1.6, w: 3.28, h: 5.4,
        fill: { color: theme === "dark" ? "0F172A" : "FFFFFF" },
        line: { color: accent, transparency: 75 },
        radius: 18
      });

      const visuals = (Array.isArray(s.visuals) ? s.visuals : []).slice(0, 4);
      const layoutHint = s.layoutHint ? String(s.layoutHint) : "";
      const teacherNotes = s.teacherNotes ? String(s.teacherNotes) : "";

      const rightLines = [];
      rightLines.push("VISUALS");
      if (visuals.length) visuals.forEach((v) => rightLines.push(`• ${v}`));
      else rightLines.push("• (Add diagram/icon)");

      if (layoutHint) {
        rightLines.push("", "LAYOUT");
        rightLines.push(layoutHint.slice(0, 140));
      }

      if (teacherNotes) {
        rightLines.push("", "TEACHER");
        rightLines.push(teacherNotes.slice(0, 220));
      }

      slide.addText(rightLines.join("\n"), {
        x: 9.48, y: 1.85, w: 2.85, h: 5.0,
        fontSize: 11.5, color: theme === "dark" ? "E2E8F0" : "0F172A",
        valign: "top"
      });
    });

    const buf = await pptx.write("nodebuffer");

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    );
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${title.replace(/[^a-z0-9 _-]/gi, "").replace(/\s+/g, "-").slice(0, 60) || "Elora-Slides"}.pptx"`
    );

    return res.status(200).send(buf);
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: "Failed to generate PPTX." });
  }
}
