import { Document, Packer, Paragraph, HeadingLevel, TextRun } from "docx";

export default async function handler(req, res) {
  if (req.method !== "POST")
    return res.status(405).json({ error: "Method not allowed" });

  try {
    const { title, content } = req.body;

    const doc = new Document({
      sections: [
        {
          children: [
            new Paragraph({
              text: title || "Elora Lesson Export",
              heading: HeadingLevel.HEADING1,
            }),
            new Paragraph({
              text: "Generated by Elora AI Assistant",
              heading: HeadingLevel.HEADING3,
            }),
            ...content.split("\n").map(
              line =>
                new Paragraph({
                  children: [new TextRun(line)],
                })
            ),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", 'attachment; filename="Elora-Lesson.docx"');
    res.send(buffer);

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to generate DOCX" });
  }
}
